# Generated by Django 4.2.29 on 2026-03-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
