# Generated by Django 4.2.29 on 2026-03-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('issuer', models.CharField(max_length=100)),
                ('issuer_logo', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('certificate_link', models.URLField(blank=True, null=True)),
                ('date_earned', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='api.technology'),
        ),
    ]
