# Generated by Django 4.2.29 on 2026-03-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_certification_alter_project_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacante_id', models.CharField(max_length=100, unique=True)),
                ('empresa', models.CharField(max_length=150)),
                ('puesto', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=150)),
                ('link', models.URLField(max_length=500)),
                ('ultima_vista', models.DateTimeField(auto_now_add=True)),
                ('habilidades_ia', models.TextField()),
                ('probabilidad_ia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_es', models.CharField(default='Disponible para proyectos', max_length=150)),
                ('status_en', models.CharField(default='Available for projects', max_length=150)),
            ],
        ),
    ]
