# Generated by Django 4.2.29 on 2026-03-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_jobopportunity_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
