# Generated by Django 4.2.29 on 2026-03-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_jobopportunity_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='probabilidad_ia',
            field=models.CharField(default='MEDIA', max_length=20),
        ),
    ]
