# Generated by Django 4.2.29 on 2026-03-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_jobopportunity_probabilidad_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='skills_faltantes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
