# Generated by Django 4.2.29 on 2026-03-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_jobopportunity_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='modalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='portal_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='salario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='tiempo_publicado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='tipo_empleo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
