server {
    listen 80;
    server_name silvadata.me www.silvadata.me;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name silvadata.me www.silvadata.me;

    ssl_certificate /etc/nginx/ssl/silvadata_full.crt;
    ssl_certificate_key /etc/nginx/ssl/silvadata.key;

    # VITAL: Carga los tipos de archivo (evita el error text/html)
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # 1. Silva-OS (n8n) - PRIORIDAD MÁXIMA
    location ^~ /n8n/ {
        proxy_pass http://n8n_silva:5678; # Usamos el container_name
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /n8n;

        proxy_buffering off;
        proxy_set_header X-Accel-Buffering no;
        proxy_read_timeout 600s;
        proxy_intercept_errors off;
    }

    # 2. API Django
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. React Frontend - CATCH-ALL
    # Al estar al final, solo atrapa lo que no entró en /n8n/ o /api/
    location / {
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /media/ {
        alias /app/media/;
    }
}